spring:


  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1qazzxcvbnm~
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:

    timeout: 10000ms

    host: 127.0.0.1

    port: 6379

    database: 0


    lettuce:
      pool:

        max-active: 1024

        max-wait: 10000ms

        max-idle: 200

        min-idle: 5

  web:
    resources:
      add-mappings: true
      chain:
        cache: true
        enabled: true
        compressed: true
      cache:
        cachecontrol:
          max-age: 3600
      static-locations: classpath:/static/

  rabbitmq:
    host: localhost

    username: guest
    password: guest
    virtual-host: /
    port: 5672
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true

    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 10000ms
        multiplier: 1

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.msp.seckill.pojo

logging:
  level:
    com.msp.seckill.mapper: debug
